# Generated by Django 5.1.6 on 2025-05-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('registration_date', models.DateField()),
                ('active_membership', models.BooleanField(default=True)),
                ('membership_type', models.CharField(choices=[('monthly', 'monthly'), ('annual', 'annual')], max_length=20)),
                ('membership_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'entry_time'), name='unique_attendance_per_day')],
            },
        ),
    ]
