# Generated by Django 5.1.6 on 2025-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'efectivo'), ('transfer', 'transferencai')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(choices=[('monthly', 'mensual'), ('annual', 'anual')], max_length=20),
        ),
    ]
