# Generated by Django 5.1.6 on 2025-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_create_employee_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
