# Generated by Django 5.1.6 on 2025-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operational', 'operacional'), ('under_maintenance', 'bajo mantenimiento')], max_length=30),
        ),
    ]
